### ISSUE TITLE
ERROR求助

### ISSUE THREAD

**Issue by zerodq2019** [go-olive/olive#120]
.\olive.exe run -f config-1669872402.toml
INFO[2022-12-01 13:37:44] dispatch add monitor                          id=shigetora pf=twitch
INFO[2022-12-01 13:37:44] dispatch remove recorder                      id=shigetora pf=twitch
INFO[2022-12-01 13:37:44] monitor start                                 id=shigetora pf=twitch
INFO[2022-12-01 13:37:56] live status changed                           id=shigetora new=true old=false pf=twitch
INFO[2022-12-01 13:37:56] dispatch add recorder                         id=shigetora pf=twitch
INFO[2022-12-01 13:37:56] recorder start                                id=shigetora pf=twitch
INFO[2022-12-01 13:37:56] dispatch remove monitor                       id=shigetora pf=twitch
INFO[2022-12-01 13:37:56] split program starts...
INFO[2022-12-01 13:37:56] parser-monitor program starts...
INFO[2022-12-01 13:37:56] monitor stop                                  id=shigetora pf=twitch
INFO[2022-12-01 13:37:57] record start                                  id=shigetora pf=twitch rn="oj streamer (fake) 251"
DEBU[2022-12-01 13:37:58] streamlink working                            out="D:\\lubo\\olive_v0.5.0_windows_386\\[shigetora][oj streamer (fake) 251][2022-12-01 13-37-57].flv"
ERRO[2022-12-01 13:37:58] rm small file failed(stat): CreateFile D:\lubo\olive_v0.5.0_windows_386\[shigetora][oj streamer (fake) 251][2022-12-01 13-37-57].flv: The system cannot find the file specified.
INFO[2022-12-01 13:37:58] dispatch add monitor                          id=shigetora pf=twitch
INFO[2022-12-01 13:37:58] dispatch remove recorder                      id=shigetora pf=twitch
INFO[2022-12-01 13:37:58] monitor start                                 id=shigetora pf=twitch
INFO[2022-12-01 13:37:58] live status changed                           id=shigetora new=true old=false pf=twitch
INFO[2022-12-01 13:37:58] dispatch add recorder                         id=shigetora pf=twitch
INFO[2022-12-01 13:37:58] recorder start                                id=shigetora pf=twitch
INFO[2022-12-01 13:37:58] dispatch remove monitor                       id=shigetora pf=twitch
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x6547ab]

goroutine 15 [running]:
os.(*Process).signal(0x0, {0x102e458, 0x1512ca4})
        /opt/hostedtoolcache/go/1.18.7/x64/src/os/exec_windows.go:49 +0x3b
os.(*Process).Signal(...)
        /opt/hostedtoolcache/go/1.18.7/x64/src/os/exec.go:138
os.(*Process).kill(...)
        /opt/hostedtoolcache/go/1.18.7/x64/src/os/exec_posix.go:67
os.(*Process).Kill(...)
        /opt/hostedtoolcache/go/1.18.7/x64/src/os/exec.go:123
github.com/go-olive/olive/engine/parser.(*streamlink).Parse(0x128dcd80, {0x128ee720, 0x1f}, {0x14c1fd40, 0x5d})
        /home/runner/work/olive/olive/engine/parser/streamlink.go:61 +0x2eb
github.com/go-olive/olive/engine/recorder.(*recorder).record(0x12851480)
        /home/runner/work/olive/olive/engine/recorder/recorder.go:178 +0xd13
github.com/go-olive/olive/engine/recorder.(*recorder).run(0x12851480)
        /home/runner/work/olive/olive/engine/recorder/recorder.go:209 +0xaf
created by github.com/go-olive/olive/engine/recorder.(*recorder).Start
        /home/runner/work/olive/olive/engine/recorder/recorder.go:56 +0x11d

win11平台 olive0.5.0版本 powershell里运行的遇到的问题无法使用，求作者大大救救

**Comment by NoodlesStamps** [comment]
我在Docker上运行它，我也得到了同样的错误。
